### ISSUE TITLE
Crashing on show startup

### ISSUE THREAD

**Issue by SuperChronos** [Loukious/StremioDiscordRichPresence#2]
Getting consistent crashing on media startup, crash log attached. Issue is fixed if I just delete the DWrite.dll
[logs.txt](https://github.com/user-attachments/files/17020270/logs.txt)

**Comment by DozerUnknown** [comment]
same issue

**Comment by DSTTRK** [comment]
any updates ?

**Comment by Loukious** [comment]
> any updates ?

Try uploading your version of Stremio. My version seems to work fine with my mod.

**Comment by Loukious** [comment]
Upload it to Google drive and post the link.

**Comment by DSTTRK** [comment]
i gave you access

**Comment by oTerminal** [comment]
Hello. Just wanted to come in here and say I've been experiencing the same issue. I'm on version 4.4.168.

**Comment by DSTTRK** [comment]
i'm signed in
it windows 10
i tried disabling my anti viruis same thing
the rich presence does work in the idle peroid where it says browsing
but the second i press on a show the timer stops and around 5 seconds it kicks me

**Comment by Loukious** [comment]
Update: The issue is most likely RD related. If anyone can land me theirs or buy me the minimum offer, I can most likely fix it. Contact me on Discord: Loukios.

**Comment by DSTTRK** [comment]
3 years ago the first time i used stremio i literally ran through every add-on that says "torrent" and added it
have heard of real-debrid but don't know what it's
![image](https://github.com/user-attachments/assets/98c73b1a-741c-42f3-9394-b5e851fd760d)
![image](https://github.com/user-attachments/assets/879379b8-eff2-4e18-8352-1fa2fd576ef9)

**Comment by DSTTRK** [comment]
update
one of the add-ons is defiantly the reason
my friend had some same as me some not but flawlessly worked for him
![image](https://github.com/user-attachments/assets/15069d23-c49b-4130-aaed-eb6b385216c0)

**Comment by Loukious** [comment]
> update one of the add-ons is defiantly the reason my friend had some same as me some not but flawlessly worked for him ![image](https://private-user-images.githubusercontent.com/154666145/385382338-15069d23-c49b-4130-aaed-eb6b385216c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzE4NjksIm5iZiI6MTczMTQzMTU2OSwicGF0aCI6Ii8xNTQ2NjYxNDUvMzg1MzgyMzM4LTE1MDY5ZDIzLWM0OWItNDEzMC1hYWVkLWViNmIzODUyMTZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNzEyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjA0MDFjNzk5M2RjYmIxMGM3ZjhhNjQ3OWQ2MTI2MmZlZTE4YmRlODliZGMyMzhmODI1OTNiNDA1NzIxOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qN81aU2y6-8rPSRf3Sibj9Emqx3xsMh5XEC7PIL3_g8)

Are you both on windows 11?

**Comment by DSTTRK** [comment]
nah only he's windows 11

**Comment by Loukious** [comment]
> nah only he's windows 11

Found the bug. Seems like the issue was happening on Windows 10. Try this new version https://github.com/Loukious/StremioDiscordRichPresence/releases/tag/v0.0.3

**Comment by oTerminal** [comment]
> > nah only he's windows 11
> 
> Found the bug. Seems like the issue was happening on Windows 10. Try this new version https://github.com/Loukious/StremioDiscordRichPresence/releases/tag/v0.0.3

I'm on Windows 11 but am experiencing the same issue. I do use real-debrid though so I can provide my login if necessary.

**Comment by Loukious** [comment]
> > > nah only he's windows 11
> > 
> > 
> > Found the bug. Seems like the issue was happening on Windows 10. Try this new version [`v0.0.3` (release)](https://github.com/Loukious/StremioDiscordRichPresence/releases/tag/v0.0.3)
> 
> I'm on Windows 11 but am experiencing the same issue. I do use real-debrid though so I can provide my login if necessary.

Weird I tried AllDebrid and it worked fine on my PC. Send me a friend request on Discord. Username: Loukios.

**Comment by DSTTRK** [comment]
great work it's working as expected
thank you wael !
![image](https://github.com/user-attachments/assets/0a6d64e1-4078-40ed-9aee-bbdaa8235cad)

**Comment by oTerminal** [comment]
Added you @Loukious.

**Comment by Loukious** [comment]
Issue seems to be solved.
